version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dwh_test
      POSTGRES_PASSWORD: dwh_test
      POSTGRES_DB: dwh_test
    volumes:
      - dwh-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dwh_test"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  dwh-volume:
