dag:
  max_active_runs: 1  # maximum number of active DAG runs
  max_active_tasks: 16  # number of task instances allowed to run concurrently
  default_args:
    max_active_tis_per_dag: 1  # number of concurrent running task instances across dag_runs per task.
    retries: 0  # number of retries that should be performed before failing the task
    retry_delay: !timedelta  # delay between retries
      minutes: 1
    execution_timeout: !timedelta  # max time allowed for the execution of this task instance, if it goes beyond it will raise and fail.
      minutes: 10
  start_date: !relativedate
    datetime: now
    interval:
      hours: 8
  end_date: !relativedate
    datetime: now
    interval:
      hours: 6
  doc_md: 'flow/dags/api_gharchive/README.md'
  description: GitHub archive download
  catchup: True
  schedule: '0 * * * *'

default:
  gharchive_operator: &gharchive_operator 'dags.api_gharchive.operators.gharchive_operator.GhArchiveOperator'
  sql_executor_operator: &sql_executor_operator 'dags.sql_executor.operators.sql_executor_operator.SqlExecutorOperator'
  clickhouse_local: &clickhouse_local clickhouse_local
  clickhouse_local_shard_1: &clickhouse_local_shard_1 clickhouse_local_shard_1
  clickhouse_local_shard_2: &clickhouse_local_shard_2 clickhouse_local_shard_2

tasks:
  - operator: *gharchive_operator
    operator_params:
      task_id: load_in_snp_raw
      task_group:
        group_id: events_raw
      main_config:
        conn_id: *clickhouse_local
        schema: snp_gharchive
        table: events_raw
    downstream:
      - operator: *sql_executor_operator
        operator_params:
          task_id: load_in_snp_raw_extract_s1
          task_group:
            group_id: events_raw
          main_config:
            conn_id: *clickhouse_local_shard_1
            template: 'flow/dags/air_dag_factory/resources/load__snp_gharchive._events_raw_extract.sql.j2'
      - operator: *sql_executor_operator
        operator_params:
          task_id: load_in_snp_raw_extract_s2
          task_group:
            group_id: events_raw
          main_config:
            conn_id: *clickhouse_local_shard_2
            template: 'flow/dags/air_dag_factory/resources/load__snp_gharchive._events_raw_extract.sql.j2'

  - operator: *sql_executor_operator
    operator_params:
      task_id: load_in_stg_s1
      task_group:
        group_id: events
      main_config:
        conn_id: *clickhouse_local_shard_1
        template: 'flow/dags/air_dag_factory/resources/load__stg_gharchive._events.sql.j2'
    upstream: ['events_raw.load_in_snp_raw_extract_s1']

  - operator: *sql_executor_operator
    operator_params:
      task_id: load_in_stg_s2
      task_group:
        group_id: events
      main_config:
        conn_id: *clickhouse_local_shard_2
        template: 'flow/dags/air_dag_factory/resources/load__stg_gharchive._events.sql.j2'
    upstream: ['events_raw.load_in_snp_raw_extract_s2']
