dag:
  max_active_runs: 1  # maximum number of active DAG runs
  max_active_tasks: 16  # number of task instances allowed to run concurrently
  default_args:
    max_active_tis_per_dag: 1  # number of concurrent running task instances across dag_runs per task.
    retries: 0  # number of retries that should be performed before failing the task
    retry_delay: !timedelta  # delay between retries
      minutes: 1
    execution_timeout: !timedelta  # max time allowed for the execution of this task instance, if it goes beyond it will raise and fail.
      minutes: 10
  start_date: !date
    datetime: now
    interval:
      hours: 7
  end_date: !date
    datetime: now
    interval:
      hours: 5
  doc_md: 'flow/dags/api_gharchive/README.md'
  description: GitHub archive download
  catchup: True
  schedule: '0 * * * *'

default:
  operator: &operator 'dags.api_gharchive.operators.gharchive_operator.GhArchiveOperator'
  conn_id: &conn_id clickhouse_local

tasks:
  - operator: *operator
    operator_params:
      task_id: load_in_snp
      task_group:
        group_id: events
      main_config:
        conn_id: *conn_id
        schema: snp_gharchive
        table: events_raw
