dag:
  start_date: !date
    datetime: now
    interval:
      days: 2
  doc_md: 'flow/dags/sql_executor/README.md'
  description: Manual execute migration.
  catchup: False
  schedule:

tasks:
  - operator: dags.sql_executor.operators.sql_executor_operator.SqlExecutorOperator
    operator_params:
      task_id: t1
      main_config:
        conn_id: clickhouse_local
        template: 'flow/migration/t.sql'
