dag:
  max_active_runs: 1  # maximum number of active DAG runs
  max_active_tasks: 16  # number of task instances allowed to run concurrently
  default_args: !include_yaml
    'flow/dags/air_dag_factory/configs/_default_args.yaml'
  start_date: !relativedate
    datetime: now
    interval:
      days: 1
  doc_md: 'flow/dags/sql_executor/README.md'
  description: Manual execute migration.
  catchup: False
  schedule:

default:
  sql_executor_operator: &sql_executor_operator 'dags.sql_executor.operators.sql_executor_operator.SqlExecutorOperator'
  clickhouse_local_admin: &clickhouse_local_admin clickhouse_local_admin

tasks:
  - operator: *sql_executor_operator
    operator_params:
      task_id: 1.databases
      task_group:
        group_id: clickhouse
      main_config:
        conn_id: *clickhouse_local_admin
        template: 'flow/migration/1.databases.sql'
    downstream:
      - operator: *sql_executor_operator
        operator_params:
          task_id: 2.roles_users
          task_group:
            group_id: clickhouse
          main_config:
            conn_id: *clickhouse_local_admin
            template: 'flow/migration/2.roles&users.sql'
        downstream:
          - operator: *sql_executor_operator
            operator_params:
              task_id: 3.snp_gharchive
              task_group:
                group_id: clickhouse
              main_config:
                conn_id: *clickhouse_local_admin
                template: 'flow/migration/3.snp_gharchive.sql'
            downstream:
              - operator: *sql_executor_operator
                operator_params:
                  task_id: 4.stg_gharchive
                  task_group:
                    group_id: clickhouse
                  main_config:
                    conn_id: *clickhouse_local_admin
                    template: 'flow/migration/4.stg_gharchive.sql'
