version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
#    networks:
#      - ch_minio
    depends_on:
      - minio
    volumes:
      - ch-db-volume:/var/lib/clickhouse
      - ./configs/z.storage_config.xml:/etc/clickhouse-server/config.d/z.storage_config.xml
      - ./log/clickhouse-server:/var/log/clickhouse-server

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'
#    networks:
#      - ch_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
      MINIO_DEFAULT_BUCKETS: chbucket

volumes:
  ch-db-volume:
  minio_data:
    driver: local

#networks:
#  ch_minio:
#    driver: bridge
